# Generated by Django 5.1.7 on 2025-05-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_user_address_user_date_of_birth_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
